services:
  votumserver:
    image: votumserver
    build:
      context: .
      dockerfile: Dockerfile
  postgresdb:
    image: postgres:15
    environment:
      POSTGRES_DB: votumDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: nicepassword
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: